Feature/money sql
inudevtech/metaverseplugin pull request #24
Opened 2022-05-18 16:14 UTC by toru-toruto

resolve #11

2022-05-18 18:18 UTC, toru-toruto commented
DatabaseUtilに書いた、データの存在チェック
`int result = resultSet.isClosed() ? 0 : resultSet.getInt("amount");`
試したところでは`isClosed()`で思い通りに動いたけれど、本当にこれで合っている根拠がないです

2022-05-18 22:01 UTC, kumitatepazuru requested changes
早速有り難うございます！
いくつか修正お願いします..!

2022-05-18 22:01 UTC, kumitatepazuru commented on src/main/java/tech/inudev/metaverseplugin/utils/DatabaseUtil.java
> +            int result = resultSet.isClosed() ? 0 : resultSet.getInt("amount");
ここ、`isclosed`じゃなくて`next`な気がします

2022-05-18 22:01 UTC, kumitatepazuru commented on src/main/java/tech/inudev/metaverseplugin/utils/DatabaseUtil.java
> +            int result = resultSet.isClosed() ? 0 : resultSet.getInt("amount");
存在しなかった場合は0ではなくnullを投げてほしいです！

2022-05-18 22:01 UTC, kumitatepazuru commented on src/main/java/tech/inudev/metaverseplugin/define/Money.java
>      public Money(String bankName) {
今回のPRとは直接的には関係ないのですが、セキュリティの関係で、this.bankName内がUUIDの構造だったらエラーを吐くというコードにしてほしいです。(`IllegalArgumentException`あたりが妥当？)

2022-05-18 22:01 UTC, kumitatepazuru commented on src/main/java/tech/inudev/metaverseplugin/define/Money.java
> +    public void remove(int value) {
処理が正常にできたら（お金が足りたら）booleanでtrue、失敗したらfalseを返すように変更していただきたいです。

2022-05-18 22:01 UTC, kumitatepazuru commented on src/main/java/tech/inudev/metaverseplugin/define/Money.java
>      public void push() {
こちらも、処理が正常にできたら（emptyじゃなかったらnullじゃなかったら等）booleanでtrue、失敗したらfalseを返すように変更していただきたいです。

2022-05-19 05:15 UTC, toru-toruto commented
指摘箇所修正しました。また、Moneyの`add()`で負数を入れると負の金額が発生し得るので修正しました。
再度チェックお願いします！

2022-05-19 07:37 UTC, kumitatepazuru requested changes
早急な修正ありがとうございます！
まだ、少し変更点がありますので修正お願いします。

2022-05-19 07:37 UTC, kumitatepazuru commented on src/main/java/tech/inudev/metaverseplugin/define/Money.java
> +        String regex = "[a-f0-9]{8}-[a-f0-9]{4}-[0-9][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}";
regexは`[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}`な気がします

2022-05-19 07:37 UTC, kumitatepazuru commented on src/main/java/tech/inudev/metaverseplugin/define/Money.java
> +        this.amount = amount != null ? amount : 0;
口座の作成は手動で行わせたいので、口座がなかったらエラーで大丈夫です。

2022-05-19 07:37 UTC, kumitatepazuru commented on src/main/java/tech/inudev/metaverseplugin/define/Money.java
> +        this.amount = amount != null ? amount : 0;
こちらも同様に、エラーで大丈夫です

2022-05-19 07:37 UTC, kumitatepazuru commented on src/main/java/tech/inudev/metaverseplugin/utils/DatabaseUtil.java
> +            while (resultSet.next()) {
多分、Resultは長さが1か0なので（じゃなきゃ何かがおかしい）、whileじゃなくてifで大丈夫だと思います。

2022-05-19 09:38 UTC, toru-toruto commented
再度、指摘箇所を修正しました。チェックお願いします！

2022-05-19 09:48 UTC, kumitatepazuru approved these changes
問題なさそうです！ありがとうございます！
※少しだけコードの整形をさせてもらいました

2022-05-19 09:49 UTC, merged