Feature/stairs
inudevtech/metaverseplugin pull request #34
Opened 2022-05-27 16:40 UTC by toru-toruto

resolve #3

2022-05-27 17:03 UTC, toru-toruto commented
`stairs.yml` に記述された階段ブロックに座ることができる機能を実装しました。
座る処理については、座席用エンティティ（コウモリ）を生成し、それにプレイヤーが乗ることで実現しています。
以下の場合、立ち上がる処理を行います。
 * 階段に座ったプレイヤーが自分の意志で立ち上がる場合
 * 階段に座ったプレイヤーがサーバーから退出する場合
 * 階段に座ったプレイヤーがデスした場合
 * 階段ブロックが破壊された場合
 * サーバーが停止された場合
 * スケジューラによって座席用エンティティが消滅した場合（後述）

また、予期しないエラーで座席用エンティティが永続化した場合に備え、スケジューラによって、十分時間（2時間に設定）経過後に座席用エンティティが消滅するようにしました。
ご確認よろしくお願いします！

2022-05-27 22:45 UTC, kumitatepazuru commented
actionsのテストにJavaDocの記述チェックを入れたので、これを見ながらJavadocの加筆をお願いします！
https://github.com/inudevtech/metaverseplugin/runs/6632740822?check_suite_focus=true

2022-05-28 18:28 UTC, toru-toruto commented
不足していたJavaDoc記述しました。また一部修正を加えました。
再度チェックよろしくお願いします！

2022-05-28 21:41 UTC, kumitatepazuru requested changes
素晴らしすぎます！挙動も問題なさそうです！
ただ、一点だけお願いします。
座ってたってを早く繰り返すと空を飛ぶことができてしまうバグがあるので、たってから座れるまでのクールダウンの仕組みを作って欲しいです。
お願いします。

2022-05-29 00:02 UTC, toru-toruto commented
クールダウン実装しました！
再度チェックよろしくお願いします！

2022-05-29 00:23 UTC, toru-toruto commented
JavaDocまたやりました
修正します

2022-05-29 01:00 UTC, toru-toruto commented
JavaDoc通りました
再度チェックよろしくお願いします。

2022-05-29 23:03 UTC, kumitatepazuru approved these changes
完璧です！
ありがとうございます！

2022-05-29 23:03 UTC, merged