Feature/bank account
inudevtech/metaverseplugin pull request #44
Opened 2022-05-30 05:28 UTC by toru-toruto

resolve #30

2022-05-30 05:37 UTC, toru-toruto commented
口座の開設機能実装しました。
それに伴って以下の変更を加えました。
- Database上のデータの更新はUPDATEだけに
- 所持金はデータがなければ、コンストラクタで新規登録

ご確認よろしくお願いします！

2022-05-31 22:50 UTC, kumitatepazuru requested changes
遅れてすみません、数点変更箇所を記載したので修正をお願いしたいです。

2022-05-31 22:50 UTC, kumitatepazuru commented on src/main/java/tech/inudev/metaverseplugin/define/Money.java
> +            DatabaseUtil.createMoneyRecord(playerUUID.toString());
ここ、自動作成じゃなくてエラーで大丈夫です。

2022-05-31 22:50 UTC, kumitatepazuru commented on src/main/java/tech/inudev/metaverseplugin/define/Money.java
> +            throw new IllegalArgumentException("同名の口座が既に存在しています。");
この部分の判定処理、多分今後結構使っていく気がするのでstaticで`isAlreadyExists`みたいな関数を作ってそこに実装してもらえるとありがたいです。

2022-05-31 23:07 UTC, tererun commented on src/main/java/tech/inudev/metaverseplugin/define/Money.java
> +            throw new IllegalArgumentException("同名の口座が既に存在しています。");
existもisも動詞なのでメソッド名はexistsだけで良い気もします🤔

2022-05-31 23:16 UTC, tererun commented on src/main/java/tech/inudev/metaverseplugin/define/Money.java
> +            throw new IllegalArgumentException("同名の口座が既に存在しています。");
https://qiita.com/yskszk/items/5a7f99c974773f03a82a
結構この記事良い感じにまとめてくれてます

2022-06-01 04:23 UTC, toru-toruto commented on src/main/java/tech/inudev/metaverseplugin/define/Money.java
> +            throw new IllegalArgumentException("同名の口座が既に存在しています。");
感謝:pray:

2022-06-01 05:33 UTC, kumitatepazuru commented on src/main/java/tech/inudev/metaverseplugin/define/Money.java
> +            throw new IllegalArgumentException("同名の口座が既に存在しています。");
> https://qiita.com/yskszk/items/5a7f99c974773f03a82a 結構この記事良い感じにまとめてくれてます

めっちゃ助かります。ありがとうございます。

2022-06-01 05:34 UTC, toru-toruto commented
こちらまだもうちょっと修正します

2022-06-01 06:05 UTC, kumitatepazuru approved these changes
最高です！ありがとうございます～

2022-06-01 06:06 UTC, merged