Feature/member
inudevtech/metaverseplugin pull request #79
Opened 2022-06-26 02:53 UTC by kidocchy

プログラムからSQLをいじるのに慣れていなくて，検証環境づくり，バグとりに時間がかかりました。すみませぬ。

ユーザー登録，呼び出しができるようになりました。
自宅のSpigot1.18 / SQLiteで動作確認済み。

Profundus.javaのonEnable()でcreateTableを呼び出し。SQLのテーブルを準備。

LoginEvent.javaで，onPlayerJoinEventをlisten
その中で，User.getUser(Player,Boolean)でデータの呼び出し(なければ作成)と，
動作確認用に，LastLoginをメッセージで出力。

Userデータは，とりあえず初回ログイン，最終ログインなどを記録。
コミュニケーション用にmainLanguage, subLanguageのプロフィールを入れる場所は作ってありますが，
入出力の部分はないので，今後の課題。ゆくゆくは他のプロフィール項目と合わせてWebインターフェイスを用意してもいいのかなと思っています。
また，UserデータはSQLに格納しているのはもちろん，
処理高速化のために，プラグイン稼働中はインメモリで保持しています。
なので，ユーザ情報の呼び出しがあれば，インメモリを検索->なければSQLを検索->なければ新規作成
という工程になっています。

今のところデータの削除機能は実装していないので，今後の必要に応じての課題かなと。

DatabaseUtil.java
PFID.java
User.java
はその処理用バックエンド。

2022-06-28 10:09 UTC, kumitatepazuru commented
@kidocchy いい忘れてました。初回なので（ぱずる流）PRのやり方〜
一旦はGithub Actionsがpassedになるまで修正をお願いします。今のところはビルドチェックとJavadocの記入漏れの確認をしてます。もし、Actionsが動かなかったらConfrictしていると思うのでPRのメッセージに沿って修正をお願いします。
Actionsがpassedになったら、実際に自分が簡単に挙動の確認等をします。それで、問題がなさそうでしたらmergeという形をとっています。

現在はActionsがfailedになっているので、Detailsから問題部分を修正してcommitをお願いします。

2022-06-29 07:25 UTC, kidocchy commented
@kumitatepazuru はいー
すみません調べながらやってみます。

2022-06-30 01:47 UTC, kumitatepazuru commented on src/main/java/tech/inudev/profundus/listener/LoginEvent.java
> +		user.getPlayer().sendMessage("Profundus[LOGIN]/DATA_SOURCE:" + user.getSource());
プレイヤーにこのような情報は表示させなくても大丈夫です。（下の行のやつも同様）

2022-06-30 02:17 UTC, kumitatepazuru requested changes
修正ありがとうございます。数点変更していただきたい部分があるので申し訳ないですが、さらに修正をお願いします。

2022-06-30 02:17 UTC, kumitatepazuru commented on src/main/java/tech/inudev/profundus/listener/LoginEvent.java
> +		user.getPlayer().sendMessage("Profundus[LOGIN]/DATA_SOURCE:" + user.getSource());
プレイヤーにこのような情報は表示させなくても大丈夫です。（下の行のやつも同様）

2022-06-30 02:17 UTC, kumitatepazuru commented on src/main/java/tech/inudev/profundus/utils/DatabaseUtil.java
> +            System.out.println("Couldn't connect DB");
Plugin.getLogger()を使ってください。（Profundus.getLogger()で行けたはず）
https://jd.papermc.io/paper/1.18/org/bukkit/plugin/Plugin.html#getLogger()
ほかの`System.out.println`も同様の対処をお願いします。

2022-06-30 02:17 UTC, kumitatepazuru commented on src/main/java/tech/inudev/profundus/utils/DatabaseUtil.java
> +    public enum Table{
今後これは増えていくことが予想されるのでenumを`USER("USER")`のような形にして`valueOf(String)`で参照できるようにしてください。
なお、その時下の`stringToEnum`はvalueOfで代替できるので削除してください。

2022-06-30 02:17 UTC, kumitatepazuru commented on src/main/java/tech/inudev/profundus/utils/DatabaseUtil.java
> +    public static Boolean createTable(Table tableName, Boolean dropIfExists) {
上の`createMoneyTable`も合体してほしいです。
存在しても再作成は手動で行う予定ですのでその仕様は削除してください

2022-06-30 02:17 UTC, kumitatepazuru commented on src/main/java/tech/inudev/profundus/utils/DatabaseUtil.java
> +    static Boolean insertItemEntry(PFItem item, UUID newPFID, String note) {
テスト用のコメントでしたら削除をお願いします。

2022-06-30 02:17 UTC, kumitatepazuru commented on src/main/java/tech/inudev/profundus/utils/DatabaseUtil.java
> +    static Connection getConnected(){
getterになるように`getConnection`に改名をお願いします。

2022-06-30 02:17 UTC, kumitatepazuru commented on src/main/java/tech/inudev/profundus/utils/DatabaseUtil.java
> +    static ResultSet select(Table tableName, String query){
ほかにも使用しているselectがあるのでそれもこの関数へ置き換えをお願いします。

2022-06-30 02:17 UTC, kumitatepazuru commented on src/main/java/tech/inudev/profundus/utils/PFGroup.java
> +public class PFGroup extends PFAgent{
グループ機能はLuckPermsのAPIを使用する予定ですのでこちらはいったんなしでお願いします。

2022-06-30 02:17 UTC, kumitatepazuru commented on src/main/java/tech/inudev/profundus/utils/PFID.java
> +public abstract class PFID{
NamespacedKeyに似た実装な気がするのでNamespacedKeyを継承しての実装をお願いしたいです。

2022-06-30 05:14 UTC, kidocchy commented
@kumitatepazuru 
先に聞けばよかったのですが。
皆さんテスト用コードってどうしてますか？

指摘してもらった中に、
本番環境では確かにいらないんだけど、
今はまだ仕様が固まってない中、
アルファ版になる前ぐらいまで残しておきたいものがちょいちょいあるのですが。

2022-06-30 05:16 UTC, kumitatepazuru commented
今のところ特に決まってはいません。
一応、皆さんはPR前にJUnitを使ったテストコードは書いていますが、PR時までには消してます。
そこらへんは盲点だったので後ほど決めようかなと思います。（JUnitなどとプラグインがあまり相性が良くなくて決められてないのも事実）

2022-06-30 05:18 UTC, kumitatepazuru commented
指摘したもので一旦は残しておきたいものはここにリストアップしてくれれば何かしらの残す等の対策は取りますので連絡をいただければ。

2022-06-30 10:00 UTC, kidocchy commented
了解です。とりあえず，自分の考え（なぜ残しているのか）を各項目の返信に書いていきますので，それを踏まえた上で消すか残すか判断いただければ，その通り修正しようと思います。共同作業は初めてなので手探りですみません・・・。

2022-06-30 10:03 UTC, kidocchy commented on src/main/java/tech/inudev/profundus/listener/LoginEvent.java
> +		user.getPlayer().sendMessage("Profundus[LOGIN]/DATA_SOURCE:" + user.getSource());
・本番環境には，いらないと思っていました。
・開発中の動作確認用ですので，デバッグ用に適切な出力先(loggerがいいんでしょうか？）があれば，そちらへの出力でいいのかなとも思います。

2022-06-30 10:05 UTC, kidocchy commented on src/main/java/tech/inudev/profundus/utils/DatabaseUtil.java
> +            System.out.println("Couldn't connect DB");
getLoggerまで辿り着けずこうなっていました。Profundus.getLogger()試してみます，

2022-06-30 10:10 UTC, kidocchy commented on src/main/java/tech/inudev/profundus/utils/DatabaseUtil.java
> +    public enum Table{
Stringでいいところを値の選択肢を制限する目的でenumを使ってみたのですが，USER("USER")の括弧内がなくても，
USER,
PFGROUP,
みたいに列挙するだけで，Stringとのやりとりをスマートに記述できる方法ってないもんですかね。(@Getter)みたいな。
なければ，ご指摘の通り試してみます

2022-06-30 10:13 UTC, kidocchy commented on src/main/java/tech/inudev/profundus/utils/DatabaseUtil.java
> +    public static Boolean createTable(Table tableName, Boolean dropIfExists) {
合体了解

再作成は，もう少しデータベースのテーブルの仕様が固まるまで残しておきたいのですがどうでしょう。
当然，本番環境が動き出せば不要，というか，使えなくするべき機能だと思っています。

2022-06-30 10:14 UTC, kidocchy commented on src/main/java/tech/inudev/profundus/utils/DatabaseUtil.java
> +    static Boolean insertItemEntry(PFItem item, UUID newPFID, String note) {
これは，別のブランチにすべきところを使い方がわからず，作り始めたアイテム管理の実装の破片です。
とりあえず消します。

2022-06-30 10:20 UTC, kidocchy commented on src/main/java/tech/inudev/profundus/utils/DatabaseUtil.java
> +    static Connection getConnected(){
この部分は，DB接続が切れていた時に再接続するためのコードです。

で，ここは相談ですが，元々の実装では，定期的にPINGを送ってコネクションを維持しているようです。
それが確実に機能するのであれば，この接続チェックとか噛まずに，インスタンスから直接Connectionをとれば済む話なのですが・・・。

１．この再接続コードは必要か，不要か
２．ぐぐると，コネクションプールを使うのが一般的と出てくるが，実装の予定はあるか

2022-06-30 10:21 UTC, kidocchy commented on src/main/java/tech/inudev/profundus/utils/DatabaseUtil.java
> +    static ResultSet select(Table tableName, String query){
>ほかにも使用しているselectがある
の意味がピンとこないのですが，
どの部分でしょうか。

2022-06-30 10:50 UTC, kidocchy commented on src/main/java/tech/inudev/profundus/utils/PFGroup.java
> +public class PFGroup extends PFAgent{
この実装によって，実現しているorしようとしている機能として，
User(個人)とGroup(法人)をPFAgentから継承することで，
1. 区画やアイテムの所有者として個人法人どちらも入れられるようになっている
(口座も法人で持てるようにする構想もどこかで見かけたような・・・)

class PFChunk
   PFAgent owner = (User or Group) hogehoge;
-----------
  owner.sendMessage(....) みたいなことが既に可能。

2. SQLサーバーという，マイクラ本体とは別でデータを管理している=SQLサーバ側の組み方でデータ保全性の確保をしやすい
の部分が大きいかなと思っています。

現状そのAPIの方が機能は豊富でしょうし，それに乗っかることは異論ないですが，
API側の都合に振り回されないよう，
少なくとも大元のデータはこちらのデータベースで管理した方がいいように思います。

ということで，どっちかがラッパーとして働くなどメンテナンスはちょい大変だと思いますが，
独自のグループクラスを持っておくことは開発の青写真としても，今後の展望を考えても有用と思いますが，
いかがでしょう。

2022-06-30 10:51 UTC, kidocchy commented on src/main/java/tech/inudev/profundus/utils/PFID.java
> +public abstract class PFID{
ほい。それは知らないやつなので，調べてきます。

2022-06-30 12:17 UTC, kumitatepazuru commented on src/main/java/tech/inudev/profundus/listener/LoginEvent.java
> +		user.getPlayer().sendMessage("Profundus[LOGIN]/DATA_SOURCE:" + user.getSource());
ここでのPRは完成品を提出するためのPRでこのようなデバッグ用コードは削除してPRしてほしいというのが自分の気持ちです。これに関連することがあればその都度またテストコードを書いて、っていうのがいいのかなって思ってます。
リリース時に皆がこのコードの存在を忘れていて”バグ的存在”になっちゃうのも厄介ですし。

2022-06-30 12:18 UTC, kumitatepazuru commented on src/main/java/tech/inudev/profundus/utils/DatabaseUtil.java
> +    public enum Table{
そもそも`valueOf`はかっこつけてなくても行けるみたいですね
https://techacademy.jp/magazine/33623

2022-06-30 12:21 UTC, kumitatepazuru commented on src/main/java/tech/inudev/profundus/utils/DatabaseUtil.java
> +    public static Boolean createTable(Table tableName, Boolean dropIfExists) {
了解です。では、コメントで`TODO: `から始まる分としてリリース時に削除する事の記入をお願いします。
また、Profundusに書かれているこの関数を呼び出す部分のこのフラグをfalseにしてください。

2022-06-30 12:25 UTC, kumitatepazuru commented on src/main/java/tech/inudev/profundus/utils/DatabaseUtil.java
> +    static Connection getConnected(){
再接続コードに関して、なくてもpingを定期的に打つことによって切断されないようにしているため問題はないと踏んでいますが、万が一のため（SQLのメンテ等とかがあったりするからその時の再接続とか）そのままでお願いします。

コネクションプールはもともとclassがstaticになっていてpluginがenableになるときに接続、disableになるときに切断という処理になっているはずなのですでに実装されているかと。（やり方が違っていたら教えていただきたいです）

2022-06-30 12:26 UTC, kumitatepazuru commented on src/main/java/tech/inudev/profundus/utils/DatabaseUtil.java
> +    static ResultSet select(Table tableName, String query){
https://github.com/inudevtech/Profundus/pull/79/files/44de3451f4326c3a8f8313ef9397b1e001430454#diff-e01330d123e0e0d8448b398d0aadcd4c5a9aa4a294deb2cceb95dc5424bc386fL137
ここですかね（もしかしたらほかにもあるかも）

2022-06-30 12:37 UTC, kumitatepazuru commented on src/main/java/tech/inudev/profundus/utils/PFGroup.java
> +public class PFGroup extends PFAgent{
1に関しては気持ちはわかるのですがLPのAPIが強力すぎて運営、という観点でも非常に便利なので向こうのAPIから継承という形で実装したほうがいいかもしれないというのが自分の意見です。
2に関してはLPもMySQLを使用したデータ管理が可能で、データ同期などの機能も豊富です。
APIの仕様が変わる、というのはまずありえないと考えてよいと思うので（考えると多分きりがない）LPの実装で行きたいというのが思いです。

正直、このプロジェクトがどのくらいの大きさになるのかが全然わからないので既存システムのメンテをできるだけ減らして新規仕様の作成等に回したい、というのがあります。

2022-06-30 14:11 UTC, kidocchy commented on src/main/java/tech/inudev/profundus/utils/DatabaseUtil.java
> +    static Connection getConnected(){
コネクションプールに関して，確かに調べてみると，現実装でも，一度接続したものを使い回すという意味では一種のコネクションプーリングと言うようですね。

私のイメージとしては，プールしておく，つまり溜めておく場所に，あらかじめ接続されたインスタンス的なものを５個とか１０個とか持っておいて，それを管理するクラスがある。そこにgetConnectionみたいに要求すると上限数までそのうち１つを貸し出してくれて，クエリを実行して，closeすると返却される。
背景には，
・タスクごとにconnect/closeするのが本当はいいらしい
・実際問題，そんなことしていたらオーバーヘッドで遅すぎる
というのがあるみたいです。
プールしておくことで，
・複数接続・接続数上限の管理
・DBサーバーメンテ時など，待たせておくことが可能
らしいデス。

マイクラのサーバーがシングルスレッドだと聞いたことはあるのですが，一つのconnectionを使い回して，処理が増えてきた時にどこまで確実に処理できるのかな？というのが疑問なところです。

2022-07-01 10:50 UTC, kidocchy commented on src/main/java/tech/inudev/profundus/utils/DatabaseUtil.java
> +    public enum Table{
<img width="798" alt="Screen Shot 2022-07-01 at 19 49 35" src="https://user-images.githubusercontent.com/78601427/176880732-0db4eb9d-ebca-4905-bba5-683137c72a40.png">
これでいきます。

2022-07-01 13:03 UTC, kidocchy commented on src/main/java/tech/inudev/profundus/utils/DatabaseUtil.java
> +            System.out.println("Couldn't connect DB");
Profundus(ext.JavaPlugin).getLogger()はstaticから呼ぶと怒られたので，
Profundusクラスで，public static Logger loggerというクラス変数を用意して，onEnable内でgetLogger()で格納しています。
ですので，Profundus.logger.log(Level,String)
で呼べます。

2022-07-01 14:43 UTC, kidocchy commented on src/main/java/tech/inudev/profundus/utils/PFID.java
> +public abstract class PFID{
調べてきました。
final class NamespacedKeyはプラグイン側ではなくマイクラspigot側にデータを持たせる必要があるときのkeyを生成するものですね。

今回のPFIDの実装は，例えば
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/persistence/PersistentDataContainer.html
でいうところの

`PersistentDataContainer. <T,Z> void set(NamespacedKey key, PersistentDataType<T,Z> type, Z value)
`
の，Z valueの方を生成・管理する部分になると思いますので，NamespacedKeyとは目的が違います。

細かくは，この先やっていく土地やアイテムの実装で検証しますが，おそらく上記setしておいたデータ(例えば管理ID)を
get( =profundus:pfid=, long)　注： ==内はNamespacedKeyで生成
で取り出して，
今回のPFIDクラスのメソッドgetByPFIDでProfundusプラグインの何らかのインスタンスを取得，
そこから処理をコールしていく
ということになるのでしょう。
今後使いそうなので，PFIDを入れ込む用のNamespacedKeyはクラス内で作っておくことにしました。

PS.別スレッドで質問したITEMデータの件ですが，まだ返信追えてないのですがこれで解決しそうですね。

2022-07-01 15:05 UTC, kumitatepazuru commented on src/main/java/tech/inudev/profundus/utils/DatabaseUtil.java
> +            System.out.println("Couldn't connect DB");
@kidocchy commit後で申し訳ないのですがもともと`getInstance().getLogger()`で行けるのでそちらを使っていただきたいです。申し訳ない...!

2022-07-03 22:27 UTC, kumitatepazuru requested changes
遅れました。度々すみません、一つ提案があるので確認していただければと思います。

2022-07-03 22:27 UTC, kumitatepazuru commented on src/main/java/tech/inudev/profundus/utils/User.java
> +public class User extends PFAgent{
このclass、BukkitのPlayerを継承して作ったほうが後々何かと楽そうなのでそっちにしてもいい気がするんですけどどうでしょうか

2022-07-03 23:45 UTC, kidocchy commented on src/main/java/tech/inudev/profundus/utils/User.java
> +public class User extends PFAgent{
Playerはinterfaceのようなので、
Extendではなくimplementになりますよね。
であれば、
Playerのメソッドの挙動を変えたい時に、
Overrideで変えたり、
User.foo()
User.getPlayer().bar()
という呼び出しの使い分けをしなくていいというのがメリットになると思いますが、認識あってます？

別の問題として、Userクラスは、プレイヤーがログインしていなくても、売買などでインスタンスを使えるように考えています。
その際、Bukkit.player関係は呼び出せないはずなので、その処理（NullPointerとかになるのかな？）はなんとかしなきゃな、と思っていたところです。その実装は、interfaceをimplementしない方が楽な気もしますね、、、。

2022-07-05 05:33 UTC, kidocchy commented on src/main/java/tech/inudev/profundus/utils/User.java
> +public class User extends PFAgent{
@kumitatepazuru 目的に立ち返って考えると，Playerはマイクラ内での挙動, Userはユーザー管理というところになると思うので，確かに被っているところもありつつ，とりあえず別でスタートしても良いように思いました。
上でも書きましたが，Userから呼べるメソッドは，対象者がログイン中じゃなくてもいいとしておく，というのが大きいところでしょうかね。

2022-07-14 09:09 UTC, kumitatepazuru commented on src/main/java/tech/inudev/profundus/utils/User.java
> +public class User extends PFAgent{
一週間ほど前に送ったはずだったのですがメッセージが送信されていなかったみたいなので再度送信します。遅れてしまい申し訳ないです。
そうでした、実装はNMSのCraftPlayerでしたね。
継承してほしい理由としては、似てるところがものすごい多いというのがあって、オフラインのとき等の問題はCraftOfflinePlayerを継承してやるってことでもいいのかなと思ってます。
ユーザー管理という点ではPlayer(CraftPlayer)もそういう立ち位置にあるものなのでほぼ一緒なのかな、と。

2022-07-14 09:36 UTC, tererun commented on src/main/java/tech/inudev/profundus/utils/PFAgent.java
> +package tech.inudev.profundus.utils;
パッケージおじさんです、こんにちは。
utilsパッケージは基本的にインスタンスを作らないクラスをまとめるという形が正規の形になります。
@kumitatepazuru 君の考え的にはあまりパッケージを増やしたくないという考えだったので「これはこのパッケージを作って...ごにょごにょ」みたいなことができないのでなんとも言えませんが、私的にはUser系の処理なので「users」とかにまとめたい気持ちです。

2022-07-14 09:36 UTC, tererun commented on src/main/java/tech/inudev/profundus/utils/User.java
> +package tech.inudev.profundus.utils;
これも同様にutilsっぽい扱いじゃないので〜って感じです。

2022-07-14 09:36 UTC, tererun commented on src/main/java/tech/inudev/profundus/utils/User.java
> +public class User extends PFAgent{
私の個人的な理由は`User#getPlayer`とか`User#getOfflinePlayer`とかそういうのを実装すべきかなあと思ったりしています。
kidocchyさんがいうようにOfflineになった際の処理が面倒そうということから上記な形にすべきかなあと思ったりしてます。
あと挙動忘れたんですが（違ったらすみません）プレイヤーがリログしたらPlayerインスタンスが違うものになっていた気がしなくもないので、フィールド変数にPlayerを入れるのではなく毎回`Bukkit.getPlayer`をしてあげた方がいい気もします。

2022-07-14 09:37 UTC, tererun commented
色々気になった点を書きました　コメントApproveするのわすれてました

2022-07-20 10:27 UTC, kidocchy commented on src/main/java/tech/inudev/profundus/utils/User.java
> +public class User extends PFAgent{
先週区画管理のあたりのコードを書いていたのですが，このUserクラスの役割はやはりProfundusとしてのユーザー管理＝SQLとのやりとりがメインなのではと思いました。ですので，区画の所有者として，このクラスのインスタンス(に対応したID)が格納できれば，私としては中身の実装は特にこだわりはありません。
tererun案→ getPlayer() / getOfflinePlayer() を実装してもいいですし，
第２案→ getPlayer()の中で判定して，CraftPlayer / CraftOfflinePlayerを適宜返すでもいいですし，
pazuru案→ 全部implementしてもいいですし。メンテ大変そうだけど。
要は，使う人がどう使いたいか，ですよね。
今のところ想定しているのは，

１。区画所有をセットするときに，例えばイベント駆動であれば
PFChunk#setOwner( User.getByPlayer(e.getPlayer() ) -> void

２。区画所有を判定するときに
User#isOwner( PFChunk.getByChunk( Player.getChunk() ) ) -> boolean

みたいに使うのかなぁと思っています。
ということで，どう使いたいか，という例をもらえた方が実装を考えやすいかなと思います。

2022-07-20 10:30 UTC, kumitatepazuru commented on src/main/java/tech/inudev/profundus/utils/User.java
> +public class User extends PFAgent{
@kidocchy じゃあ作業量とかを考えて一旦てれるんさんのget~()を実装で行きましょうか。
それでやってってプログラムが読みづらくなってきた！とかになったら適宜変更するって感じで。

2022-07-20 10:31 UTC, kidocchy commented on src/main/java/tech/inudev/profundus/utils/PFAgent.java
> +package tech.inudev.profundus.utils;
パッケージの管理どうしているのかわからんので，とりあえずutilに入れていました。
ゆくゆくはデーターベースいじる系（ユーザー・お金・所有権）はそれでまとめたらいいのかなと思っていたところでした，

2022-07-20 10:32 UTC, kumitatepazuru commented on src/main/java/tech/inudev/profundus/utils/PFAgent.java
> +package tech.inudev.profundus.utils;
この際なのでデータベースいじる系のパッケージ作っちゃいましょうか
utilがごちゃごちゃしてもあれですし。
名前はおまかせしますｗ

2022-07-23 10:45 UTC, kidocchy commented on src/main/java/tech/inudev/profundus/utils/PFAgent.java
> +package tech.inudev.profundus.utils;
パッケージ変更しようと思っていたのですが，utilsだけutilではなく複数形なのなんか文化とか意味とかあります？

あと，...profundus.util(s).databaseと
...profundus.databaseと
どちらが好みですか？

2022-07-23 10:53 UTC, kumitatepazuru commented on src/main/java/tech/inudev/profundus/utils/PFAgent.java
> +package tech.inudev.profundus.utils;
なんでutilsなのかは自分も記憶にないですがおそらく単数でOKだと思います（間違ったことは言えないのでパッケージおじさん召喚しときます @tererun )
パッケージに関しては自分は下のほうが嬉しいです（長いのはちょっとやだ）

2022-07-23 12:26 UTC, tererun commented on src/main/java/tech/inudev/profundus/utils/PFAgent.java
> +package tech.inudev.profundus.utils;
呼ばれたパッケージおじさんです
正直どちらでもいいですが、私はいつも可算名詞かどうかで決めるようにしています。
パッケージの中には複数のクラスやインターフェースが入る分けですから、複数形、という気持ちです。

2022-07-24 00:03 UTC, kumitatepazuru commented on src/main/java/tech/inudev/profundus/utils/PFAgent.java
> +package tech.inudev.profundus.utils;
じゃあそのままで行きましょ〜（圧倒的適当感）

2022-07-24 09:32 UTC, kumitatepazuru requested changes
developとのconflictの修正をお願いします

2022-07-25 04:03 UTC, kidocchy commented
gitむずかしい・・・
eclipseむずかしい・・・

2022-07-26 00:23 UTC, kumitatepazuru requested changes
修正ありがとうございます。

UserクラスのLanguageとLastLoginに関してなのですが、何度も申し訳ないですがPlayerクラスの[getLocale](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Player.html#getLocale())とOfflinePlayerクラスの[getLastPlayed](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/OfflinePlayer.html#getLastPlayed())で代用できると思うので削除をお願いしたいです。

2022-07-27 01:59 UTC, kidocchy commented
反応が悪くすみません。
languageは，例えば私はenでマイクラしてますが，コミュニケーションはjpでOKです。
そういった，プロフィール情報のための準備です。

lastloginは，webインターフェイスとかからログインした時間も記録するための準備です。
メタバースなので，ゲームで全部やれよ，という気もしますが，ゲームプレイ＋webインターフェイスでフリマ，というのもありなのかな，と構想してます。

という意図を伝えたところで，要らないということであれば削除しますがどうでっしゃろ？

2022-07-27 03:06 UTC, kumitatepazuru commented
じゃあ残しましょうか（）
ただ、SubLanguageに関しては実態使わないと神に誓ってでも言えるのでこれだけ削除をお願いしたいです
お手数おかけします

2022-07-28 01:15 UTC, kumitatepazuru approved these changes
ありがとうございます。問題なさそうなのでmergeします。
何度も修正をしてくださりありがとうございました!

2022-07-28 01:15 UTC, merged