Feature/metazon
inudevtech/metaverseplugin pull request #81
Opened 2022-06-30 20:01 UTC by toru-toruto

Metazon の販売機能を実装しました。
出品アイテムを登録する部分は未実装です。

合わせて主に以下の機能を実装しました。
- draggable なアイテムの挙動調整(Gui)
- draggableなMenuItem生成メソッド(MenuItem)
- 不使用スロットを埋めるMenuItem生成メソッド(MenuItem)
  - Guiではとりあえず手動設置
  - MultiPageGuiでは自動設置
- lore, iconのSetter(MenuItem)
- Gui menuItemsの特定のiconをcloneするメソッド(Gui)
- MultiPageGuiでGui#addItemを無効に

未解決な問題
- 統合版でヘルプが表示できない(別issueを立てる)

ご確認よろしくお願いします！

2022-07-02 23:12 UTC, toru-toruto commented
もとのプルリクに追加する形ですみませんが、出品処理も実装しました。
データベース上に商品データを保存するようにしています。
保存する商品のデータは以下の通りです。
- `material`: Materialの文字列
- `enchantments`: 0個以上のエンチャント情報を保持する文字列
  - 一つのエンチャント情報の形式：`NamespacedKey:>エンチャントレベル`
  - `,`区切り
- `amount`: 商品アイテムの個数
- `price`: 商品の価格
- `seller`: 出品者

また動作テストをしたかったので、商品データをリストで取得する機能も実装してしまいました。

チェックよろしくお願いします。

2022-07-03 09:51 UTC, kumitatepazuru requested changes
確認遅れました。いくつか修正点があるので変更をお願いします。

2022-07-03 09:51 UTC, kumitatepazuru commented on src/main/java/tech/inudev/profundus/define/Gui.java
> +            final int id = Math.toIntExact(res.getClickedButtonId());
ここを消したのに何か理由ってありますか？もしかしてバグってました？（）

2022-07-03 09:51 UTC, kumitatepazuru commented on src/main/java/tech/inudev/profundus/define/Gui.java
> +            throw new IllegalArgumentException();
関数をNullableにしちゃってこの時はnullをreturnするでいいと思います。

2022-07-03 09:51 UTC, kumitatepazuru commented on src/main/java/tech/inudev/profundus/define/Gui.java
> +                        Bukkit.getScheduler().runTaskLater(Profundus.getInstance(), () -> {
この部分、即時性を求めるもの（GUI推移しないもの系）も今後出てくると思うので、2tickはOnClickの関数内で行ってほしいです。

2022-07-03 09:51 UTC, kumitatepazuru commented on src/main/java/tech/inudev/profundus/define/Metazon.java
> +                Component.text("購入モード"),
購入する、のほうがわかりやすいと思うのでそちらに変更をお願いしたいです

2022-07-03 09:51 UTC, kumitatepazuru commented on src/main/java/tech/inudev/profundus/define/Metazon.java
> +                Component.text("販売モード"),
こちらも同様販売するでお願いしたいです。

2022-07-03 09:51 UTC, kumitatepazuru commented on src/main/java/tech/inudev/profundus/define/Metazon.java
> +        Gui gui = new Gui(METAZON_TITLE + " 販売モード");
タイトルも同様に変更をお願いします。

2022-07-03 09:51 UTC, kumitatepazuru commented on src/main/java/tech/inudev/profundus/define/Metazon.java
> +                Component.text("販売ボタン"),
同様の理由で、販売する、がうれしいです。

2022-07-03 09:51 UTC, kumitatepazuru commented on src/main/java/tech/inudev/profundus/define/MultiPageGui.java
> +     */
使わせないという意味では@deprecated をつけて使った場合はIDEが警告を出すようにしてもいいかも

2022-07-03 11:11 UTC, toru-toruto commented on src/main/java/tech/inudev/profundus/define/Gui.java
> +            final int id = Math.toIntExact(res.getClickedButtonId());
これ、修正前もバグってましたけど、修正後もまだバグってました

要約すると、修正前のは統合版表示に必要なアイテムの間や後ろに不要なアイテムがaddされているとidがずれ、修正後のは前や間にaddされているとidがずれる
って感じだと思います

修正します。

2022-07-03 18:02 UTC, toru-toruto commented on src/main/java/tech/inudev/profundus/define/Gui.java
> +                        Bukkit.getScheduler().runTaskLater(Profundus.getInstance(), () -> {
OnClickってMenuItemのやつですよね？
私としては、各機能の実装者にこの謎の2tick遅延を行わせるのは混乱を生みそうだから、
ここで処理させた方がいいんじゃないかと思うのですがどうでしょう？

ちなみにこの2tick遅延は「Java→統合」の推移だけをターゲットにしているつもりではいます。強制力がないですが()
- 推移なし：当然`close`はfalse
- 「java→java」：`close`がtrueだとマウスカーソルが中央に戻ってしまうのでfalse推奨

（ `MenuItem`にそれぞれの生成メソッドを用意しておけば親切かも？）

2022-07-03 18:33 UTC, toru-toruto commented on src/main/java/tech/inudev/profundus/define/Gui.java
> +                        Bukkit.getScheduler().runTaskLater(Profundus.getInstance(), () -> {
GUIを閉じる操作終了時の処理は2tick遅延対象になってました

2022-07-03 22:23 UTC, kumitatepazuru commented on src/main/java/tech/inudev/profundus/define/Gui.java
> +                        Bukkit.getScheduler().runTaskLater(Profundus.getInstance(), () -> {
ははーん、なるほど。じゃあいったんはそのままにしましょうか。
生成メソッドに関しては優先度低で新たにissue作っときます

2022-07-04 00:02 UTC, toru-toruto commented
指摘された箇所修正しました。
idがずれるバグについては、`res.getClickedButtonId()`と`menuItems`のindexを紐づけるMapを用意して対処しました。

あと、販売確認画面でアイテムが真ん中にあってほしくなってしまったのでGUI上の位置だけ変更しました。

再度チェックよろしくお願いします。

2022-07-05 22:58 UTC, kumitatepazuru requested changes
修正ありがとうございます。
動作確認をして数点変更していただきたい部分がありましたのでお願いします。

![image](https://user-images.githubusercontent.com/43287589/177430042-b7790294-ab20-4b44-823a-e2acaf3f2978.png)
この部分、アイテムが入っているときは下の説明を消してください。
あとは売れるときには紙にエンチャントをつけてキラキラさせてもわかりやすいかもです。

![image](https://user-images.githubusercontent.com/43287589/177430164-72b4546d-5d60-4407-a490-766cb79ce010.png)
この部分、下のloreはいらないと思うので消してください。また、タイトルは100円増やすみたいなほうがいいと思います。（他のボタンも同様）
また、押したかどうかがわからないと思うので`Sound.UI_BUTTON_CLICK`を押したときに出るようにしてほしいです。（これはGuiクラスでクリックされたときに流れるようにしたほうがわかりやすいかも）

2022-07-06 22:47 UTC, toru-toruto commented
バグの対処方法を思いついたので、もう少し手を加えると思います

2022-07-07 00:44 UTC, toru-toruto commented
指摘箇所を再修正しました。

また、Shift+クリックやダブルクリックなど、左右クリック以外の操作でdraggableなmenuItemの情報が更新できていなかったので対処しました。
具体的には以下の通りです
- Metazon GUI内：draggableなスロット上で操作を行うたびにdraggableなmenuItemすべての更新処理を実行
- Metazon GUI外：左右クリック以外の操作を行うたびにdraggableなmenuItemすべての更新処理を実行

左右クリック以外の操作すべてで更新処理を実行するため、必要十分ではないですが、
draggableに関してmenuItemの情報にズレが生じない処理にはなっていると思います。

再度チェックよろしくお願いします。

2022-07-12 08:14 UTC, kumitatepazuru requested changes
確認が遅れて申し訳ないです....!
数点、バグを見つけたので修正をお願いします。

- エンチャントされたアイテムを入れたときに、何故か確認画面に行くと耐久力1が付与される（その後戻ってもその状態）
- アイテムの固有の名前がデータベース上に保存されていない

保存関係の処理はItemStackに[serialize](https://jd.papermc.io/paper/1.18/org/bukkit/inventory/ItemStack.html#serialize())という素晴らしい関数があるので(SQLに保存はserializeAsBytesが使いやすいかも)それを使うのも手です。

また、アイテムが販売できないときはクリックしたときに`Sound.ENTITY_ENDERMAN_TELEPORT`が流れるようにしてほしいです。

お願いします。

2022-07-12 15:22 UTC, toru-toruto commented
指摘された箇所修正しました。

販売できないときのSEは通常のクリック音（`Sound.UI_BUTTON_CLICK`）に重ねて流しています。
それほど違和感はないと思いますがどうでしょう？

これを重ねないようにするとなると、
`Gui#onInventoryClick`でなく各機能側でクリック音の再生を
実装させることになってしまうと思うので、
特に違和感がなければこれで行きたいと思っています。

ご確認よろしくお願いします！

2022-07-14 09:06 UTC, kumitatepazuru requested changes
確認遅れて申し訳ないです、早急な修正ありがとうございます。
音の件、了解しました。結構良さそうなのでこのままで行きましょう（）
バグ修正、確認できました。ただ、販売するアイテムを設定するときに、アイテムがインベントリに戻らず消滅してしまうバグがあったので修正してほしいです。
その際、Inventory.addItemの仕様がちょっと微妙なので #73 をついでに実装してほしいです。

また、販売をしたときにわかりやすくなにか音＋メッセージを出すようにしてほしいです。
何度も申し訳ないですが、よろしくおねがいします。

2022-07-15 23:29 UTC, toru-toruto commented
ご確認ありがとうございます。

>販売するアイテムを設定するときに、アイテムがインベントリに戻らず消滅してしまうバグがあったので修正してほしいです。

インベントリを閉じるときにアイテムが返ってこないってことですよね？
すいません、これ #73 の内容だとかん違いしてました。修正します。

その他についても了解しました。

2022-07-22 11:21 UTC, toru-toruto commented
指摘いただいた箇所を修正しました。

アイテムの返還については、以下のような実装を行いました。
- `returnOnClose==true`のMenuItemを返還する
- 未指定時、アイテムを返還する
- `cancelReturn==true` のMenuItemのクリックによってGUIが閉じられた場合、アイテムを返還しない

販売登録完了時のSEは `Sound.ENTITY_PLAYER_LEVELUP` を使用しました。

ご確認よろしくお願いします！

2022-07-23 11:42 UTC, kumitatepazuru approved these changes
問題なさそうなのでmergeします！
様々な修正ありがとうございます。

2022-07-23 11:42 UTC, merged