Feature/money
inudevtech/metaverseplugin pull request #9
Opened 2022-05-14 22:08 UTC by toru-toruto

resolve #2

2022-05-14 22:34 UTC, kumitatepazuru requested changes
早速PRありがとうございます！
いくつか修正点がありましたので、修正していただけると嬉しいです！

2022-05-14 22:34 UTC, kumitatepazuru commented on src/main/java/tech/inudev/metaverseplugin/money/Money.java
> +    public Money(int playerUUID) {
playerUUIDはintではなくUUID型ですね

2022-05-14 22:34 UTC, kumitatepazuru commented on src/main/java/tech/inudev/metaverseplugin/money/Money.java
> +    public Money(int playerUUID, String bankName, boolean isBankMoney) {
こちらも同様です

2022-05-14 22:34 UTC, kumitatepazuru commented on src/main/java/tech/inudev/metaverseplugin/money/Money.java
> +    public Money(int playerUUID, String bankName, boolean isBankMoney) {
isBankMoneyのパラメータの説明がないので加筆していただきたいです

2022-05-14 22:34 UTC, kumitatepazuru commented on src/main/java/tech/inudev/metaverseplugin/money/Money.java
> +            logging("取引するためのお金が足りません");
これはplayerUUIDのPlayerがオンライン状態（サーバーにいる時）にはプレイヤー側にも流してほしいです

2022-05-14 22:34 UTC, kumitatepazuru commented on src/main/java/tech/inudev/metaverseplugin/money/Money.java
> +public class Money {
このクラスたちはutilパッケージの中にしていただきたいです

2022-05-15 01:06 UTC, toru-toruto commented
Money丸ごと書き直したみたいな差分なってしまいました...修正箇所は指摘された部分です。
（Moneyをutilsパッケージに移動した後で、やっぱりその前にコミットしておこうとして戻したのが原因です）
見づらくて申し訳ないですが、再度レビューお願いします。

2022-05-15 01:24 UTC, kumitatepazuru commented
> Money丸ごと書き直したみたいな差分なってしまいました...修正箇所は指摘された部分です。 （Moneyをutilsパッケージに移動した後で、やっぱりその前にコミットしておこうとして戻したのが原因です） 見づらくて申し訳ないですが、再度レビューお願いします。

全然大丈夫ですよ〜

2022-05-15 01:26 UTC, kumitatepazuru requested changes
あと一点だけ修正お願いします...!

2022-05-15 01:26 UTC, kumitatepazuru commented on src/main/java/tech/inudev/metaverseplugin/utils/Money.java
> +    public Money(UUID playerUUID, String bankName) {
何度もすみません、口座の場合のplayerUUIDはいらないので消してもらえますか

2022-05-15 01:54 UTC, toru-toruto commented
口座の場合の引数playerUUIDの削除 完了しました
確認おねがいします！

2022-05-15 02:09 UTC, tererun commented
元々のぱずるさんの指示とここまで書いていただいてこれかよ！って感じで申し訳ないのですが、ちょっと設計的な話でこっちの方がいいのかな...？と言うのがありまして...

いわゆるMoneyの形態（例えば`playerUUID`で指定する場合と`bankName`で指定する場合みたいに）を後々増やすといった時にMoneyクラスに全てまとめてしまうとごちゃごちゃになってしまうなと思ってしまったので、Moneyクラスをinterfaceで定義してあげて、implementsする形でやるべきなのかなあとか思ったりしました。どうでしょうか...？
おそらく今の状態だとあまり効果がでない気がしますが、通貨の種類を増やしたりだとか形態の中に新しい値を追加したりするときにこちらの方が便利なのかなと思っています。

（あと`util`に追加せずに`money`っていう新しいパッケージ作った方がいいかなと）

簡単な例を示すとこんな感じですね

```java
public interface Money {
    long getBalance();
}
```

```java
public class PlayerMoney implements Money {

    @Getter private UUID playerUUID;
    private long balance;

    @Override
    public long getBalance() {
        return balance;
    }

}
```

```java
public class BankMoney implements Money {

    @Getter private String bankName;
    private long balance;

    @Override
    public long getBalance() {
        return balance;
    }

}
```

2022-05-15 02:16 UTC, kumitatepazuru commented
それもありなんですが、犬田の構想シートを見ている限りではMoneyの形態は２種類固定になると思われるので一旦はこのままで大丈夫です。また必要になったら変更していきましょう（あんまり良くないですがｗ）。

形態を増やす＝プレイヤーも覚えなくてはいけない＝敷居が高くなる
みたいなところもあるのでそういう観点からでも２種類のままで行くかなぁって思ってます。

moneyパッケージに関しても、作ってもいいかなと思ったのですが今のところはこのクラス一つだけになりそうなので（そこまで複雑なこともやる予定ないし）これで大丈夫です。
わざわざ指摘していただいたのにすみません。

2022-05-15 02:18 UTC, kumitatepazuru requested changes
何度も申し訳ない...！最後にこれだけお願いします！

2022-05-15 02:18 UTC, kumitatepazuru commented on src/main/java/tech/inudev/metaverseplugin/utils/Money.java
> +            if (player.isOnline()) {
ここ、playerUUIDが入ってないときにﾇﾙﾎﾟになる気がするのでnullチェックをするように修正お願いします。

2022-05-15 02:18 UTC, tererun commented
いえいえ〜大丈夫ですよ

ええとパッケージについてですが、それだったらutilじゃなくてconstとかの方がいいのかなと思ったりします。
utilっていうのはstaticなメソッドとかを入れて置く場所でどこからアクセスできる形を示すので、そちらの方がいいかと...

2022-05-15 07:21 UTC, toru-toruto commented
とりあえずパッケージの方の議論は保留と受け取って、指摘箇所だけ修正しましたー

2022-05-15 07:23 UTC, kumitatepazuru approved these changes
ありがとうございます！一旦パッケージに関してはDiscord上で決めることにしようかなと思います。

2022-05-15 07:23 UTC, merged