Feature/move1
inudevtech/metaverseplugin pull request #99
Opened 2022-08-13 19:53 UTC by kumitatepazuru

feature #93

2022-08-16 12:50 UTC, toru-toruto commented
`feature/move1`ブランチをコンパイルして、paperサーバで動かそうとしたんですが起動時にエラーが発生しました。
コンパイル時にはエラーは出ないのですが、依存関係の設定ミスなのでしょうか？

エラーログは以下の通りです。

<details>
<summary>error-log</summary>

``
[21:31:25 ERROR]: Could not load 'plugins\Profundus-1.0-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: tech/inudev/profundus/profundusLib/interfaces/JavaPluginWithConfigHandler
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:415) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:323) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:418) ~[paper-1.18.2.jar:git-Paper-333]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[paper-1.18.2.jar:git-Paper-333]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-333]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-333]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: tech/inudev/profundus/profundusLib/interfaces/JavaPluginWithConfigHandler
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:197) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:71) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: tech.inudev.profundus.profundusLib.interfaces.JavaPluginWithConfigHandler
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:197) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:71) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        ... 7 more
``
</details>

2022-08-16 21:14 UTC, kumitatepazuru commented
もしかしたらこっちも鯖に突っ込まなきゃ動かないかもです
https://github.com/Profundus-inudev/Profundus-lib

2022-08-17 01:23 UTC, tererun commented
https://github.com/johnrengelman/shadow

こいつ使ってshadowJarでコンパイルするようにした方が楽かもしれないですねー
fatJar作ってあげて、NoClassDefが出ないようにするやつです

2022-08-17 01:24 UTC, kumitatepazuru commented
それは思ったｗ
ちなみに、そこらへんの知識ほぼ無い民だからもしやり方知ってたらやってほしかったりするんだけど可能？

2022-08-17 01:25 UTC, tererun commented
> それは思ったｗ
> ちなみに、そこらへんの知識ほぼ無い民だからもしやり方知ってたらやってほしかったりするんだけど可能？

午後には帰るのでやっておきますー

2022-08-17 09:50 UTC, tererun commented
とりあえず追加しておきました、デバッグする暇はないので誰かビルドしていただいて動くか試していただけると幸いです🫠

2022-08-23 10:46 UTC, toru-toruto commented
`shadowJar`タスクで生成して、おそらく正常に動きました！
ありがとうございます！

2022-08-24 08:48 UTC, toru-toruto requested changes
移行について、実装的には問題なさそうです。
ただ、インデントがおかしくなっているところが多々あるので、Profundus-libの方も含め自動整形かけておいていただきたいです。

また、おそらくこのプルリクに関係はないとは思うのですが、以下のような警告・エラーが発生したので一応報告です。
（後者のエラーについては、おそらくMetazonの実装での私のミスです。修正の見当もついてるのでProfundus-libの方でissue立てて修正します）

<details>
<summary>ログイン時に発生する警告</summary>

``
[04:28:57 WARN]: [Profundus] org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (near "WHERE": syntax error)
        at org.sqlite.core.DB.newSQLException(DB.java:1030)
        at org.sqlite.core.DB.newSQLException(DB.java:1042)
        at org.sqlite.core.DB.throwex(DB.java:1007)
        at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
        at org.sqlite.core.NativeDB.prepare(NativeDB.java:137)
        at org.sqlite.core.DB.prepare(DB.java:257)
        at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:45)
        at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
        at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:25)
        at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35)
        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)
        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
        at Profundus-1.0-SNAPSHOT-all.jar//tech.inudev.profundus.database.DBUUser.update(DBUUser.java:91)
        at Profundus-1.0-SNAPSHOT-all.jar//tech.inudev.profundus.database.User.updateDB(User.java:165)
        at Profundus-1.0-SNAPSHOT-all.jar//tech.inudev.profundus.database.User.updateLastLogin(User.java:193)
        at Profundus-1.0-SNAPSHOT-all.jar//tech.inudev.profundus.listener.LoginEvent.onPlayerJoinEvent(LoginEvent.java:23)
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor20.execute(Unknown Source)
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669)
        at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:363)
        at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:305)
        at net.minecraft.server.network.PlayerConnection.c(PlayerConnection.java:305)
        at net.minecraft.network.NetworkManager.a(NetworkManager.java:567)
        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:201)
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1620)
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:483)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1455)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1225)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
        at java.base/java.lang.Thread.run(Thread.java:833)
``
</details>

<details>
<summary>Metazon アイテム未指定で販売するボタンをクリックした時に発生</summary>

``
[04:30:39 ERROR]: Could not pass event InventoryClickEvent to Profundus v1.0-SNAPSHOT
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.clone()" because the return value of "tech.inudev.profundus.profundusLib.gui.MenuItem.getIcon()" is null
        at tech.inudev.profundus.profundusLib.gui.Gui.cloneItemStack(Gui.java:220) ~[Profundus-1.0-SNAPSHOT-all.jar:?]
        at tech.inudev.profundus.define.Metazon.onSellPaperClick(Metazon.java:175) ~[Profundus-1.0-SNAPSHOT-all.jar:?]
        at tech.inudev.profundus.define.Metazon.lambda$generateSellMenu$2(Metazon.java:115) ~[Profundus-1.0-SNAPSHOT-all.jar:?]
        at tech.inudev.profundus.profundusLib.gui.Gui.onInventoryClick(Gui.java:303) ~[Profundus-1.0-SNAPSHOT-all.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor22.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-333]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2860) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-333]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1399) ~[paper-1.18.2.jar:git-Paper-333]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-333]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1376) ~[paper-1.18.2.jar:git-Paper-333]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1369) ~[paper-1.18.2.jar:git-Paper-333]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1347) ~[paper-1.18.2.jar:git-Paper-333]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1229) ~[paper-1.18.2.jar:git-Paper-333]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-333]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
``
</details>

2022-08-26 06:55 UTC, kumitatepazuru commented
返信遅れて申し訳ありません。
確認ありがとうございます。リファクタリング&警告の件、了解です。後ほど対応します。

2022-08-27 04:53 UTC, kidocchy commented
一文字削除しただけだったので，こっちにcommitしてしまいましたが，こういうのブランチ分けた方がいいんでしょうか？

2022-08-27 09:08 UTC, kumitatepazuru commented
@kidocchy 大丈夫です！ありがとうございます！
全体的なコードの確認もしてreviewもOKしてくれると幸いです！

2022-08-29 07:16 UTC, kidocchy approved these changes

2022-09-07 13:52 UTC, toru-toruto approved these changes

2022-09-07 13:55 UTC, toru-toruto commented
すいません、チェック遅くなりました
コード整形ありがとうございます！マージします！

2022-09-07 13:55 UTC, merged